controller_list:
  - name: fake_techus_move_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses per group
  - group: techus_move
    pose: techus_home