techman_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - front_left_wheel
    - front_right_wheel
    - rear_left_wheel
    - rear_right_wheel
    - shoulder_1_joint
    - shoulder_2_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    front_left_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    front_right_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rear_left_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rear_right_wheel:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1